version: '2'

services:
  default:
    image: gemini-git-browser:latest
    container_name: gemini_git_browser
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1965:1965"
    volumes:
      - /etc/letsencrypt/live/git.ritesh.ch/fullchain.pem:/app/cert/cert.pem
      - /etc/letsencrypt/live/git.ritesh.ch/privkey.pem:/app/cert/key.pem
      - /var/gitea/git/repositories:/repositories
